# Generated by Django 5.1.3 on 2025-02-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_cgst_alter_product_igst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CGST',
            new_name='cgst',
        ),
    ]
