# Generated by Django 5.1.3 on 2025-02-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_nickname_product_nick_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brandName',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='HSNCode',
            new_name='hsn_code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sellingPrice',
            new_name='selling_price',
        ),
    ]
