# Generated by Django 5.1.3 on 2025-02-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_brandname_product_brand_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cgst',
            new_name='CGST',
        ),
    ]
